schema {
  query: Query
}

type Query {
  # Запрос информации о клиенте
  client(id: String!): Client
}

# Основная сущность клиента
type Client {
  id: String!
  name: String
  age: Int
  documents: [Document] # Вложенные данные о документах клиента
  relatives: [Relative] # Вложенные данные о родственниках клиента
}

# Документ клиента
type Document {
  id: String!
  type: String
  number: String
  issueDate: String
  expiryDate: String
}

# Родственник клиента
type Relative {
  id: String!
  relationType: String
  name: String
  age: Int
}
