apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-app-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus
spec:
  selector:
    matchLabels:
      prometheus-monitored: "true"
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - interval: 10s
      targetPort: 8080
      path: /metrics
